{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "1f7eb8b4_885f6b93",
        "filename": "tools/handler.cpp",
        "patchSetId": 1
      },
      "lineNbr": 111,
      "author": {
        "id": 1000388
      },
      "writtenOn": "2023-03-15T19:04:08Z",
      "side": 1,
      "message": "So we only retry on tool exception? Should we bother retrying on blob exception as well?",
      "range": {
        "startLine": 104,
        "startChar": 0,
        "endLine": 111,
        "endChar": 24
      },
      "revId": "eeb7d7a76c8a42cd70d0b9e336cfe49203b8eb1f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}